student/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf.urls import url,include


urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('students.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

students/urls.py
from django.conf.urls import url
from .views import *
from students import views
app_name = 'students'

urlpatterns= [
	url(r'^$',views.RetrieveAll,name='RetrieveAll'),
    url(r'^student/Create/$', views.CreateStudent, name = 'CreateStudent'),
    url(r'^student/detail/(?P<pk>\d+)$',views.Retrieve,name='detail'),
    url(r'^student/delete/(?P<pk>\d+)$',views.delete,name='delete'),
    url(r'^student/update/(?P<pk>\d+)$',views.update,name='update'),

]

students/models.py
from django.db import models

class Student(models.Model):
    pic = models.ImageField(default="images.png",blank= True)
    name = models.CharField(max_length=100)
    rollno = models.CharField(max_length=10)
    classinfo = models.CharField(max_length=10)
    mothername = models.CharField(max_length=30)
    fathername = models.CharField(max_length=30)
    address = models.TextField()
    dob = models.DateField(blank=True)
    mobileno = models.IntegerField()
    email = models.EmailField()
    nationality = models.CharField(max_length=20)

    def __str__(self):
        return self.name

students/forms.py
from django import forms
from .models import Student

class Studentform(forms.ModelForm):
	address = forms.CharField(label="address",widget=forms.Textarea(attrs={'class': 'form-control','rows':'2' ,}))
	class Meta:
		model = Student
		fields = ['pic','name', 'classinfo', 'rollno', 'dob','mothername', 'fathername', 'address', 'mobileno', 'email', 'nationality']

students/views.py
from django.shortcuts import render,redirect
from .models import Student
from .forms import Studentform

def CreateStudent(request):
    form=Studentform()
    if request.method == 'POST':
        form = Studentform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('students:RetrieveAll')
        else:
            form = Studentform()
    #else:
    #    form =Studentform()
    return render(request, 'students/create.html',{'form':form})

def RetrieveAll(request):
    s = Student.objects.all().order_by('-id')
    return render(request, 'students/retall.html', {'s':s})

def Retrieve(request,pk):
    s = Student.objects.get(pk = pk)
    return render(request, 'students/detail.html', {'s':s})
def delete(request,pk):
    s = Student.objects.get(pk = pk).delete()
    return redirect('students:RetrieveAll')

def update(request,pk):
    s = Student.objects.get(pk=pk)
    form = Studentform(instance =s)
    if request.method == 'POST':
        form = Studentform(request.POST, request.FILES, instance=s)
        if form.is_valid():
            form.save()
            return redirect('students:RetrieveAll')
   
    return render(request, 'students/update.html',{'form':form})

students/templates/students/create.html

{% extends 'base.html'%}

{% block content %}
<div class=" col-md-9 col-sm-9">
 <legend>Fill The Form To Add Student</legend>
    <form class="site-form-create" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{from.media}}
      {{form.as_p}}
      <input type="submit" name="create" value="create">
    </form>
   
</div>


{% endblock %}

students/templates/students/detail.html

{% extends 'base.html'%}

{% block content %}
<div class=" col-md-12 col-sm-12">
  <br><br>
  
    <legend>Student Details </legend>
    
    <table class="table table-striped" >


 
<tbody>



 

    <tr>
    <td colspan="2"><center><img src="{{ s.pic.url }}" style="height:20%;width:20%;"></center></td>
    <tr>
    <tr>
      <u><th colspan="2"><h4><u>Basic Informations</u></h4></th>
    <tr>
    <tr>
      <td> Name </td>
      <td> {{s.name}}</td>
    </tr>
    <tr>
      <td> Class </td>
      <td> {{s.classinfo}}</td>
    </tr>
    <tr>
      <td> Roll No. </td>
      <td> {{s.rollno}}</td>
    </tr>
     <tr>
      <th colspan="2"><h4><u>Other Informations</u></h4></th>
    <tr>
    <tr>
      <td> Mother's Name </td>
      <td> {{s.mothername}}</td>
    </tr>
     <tr>
      <td> Father's Name</td>
      <td> {{s.fathername}}</td>
    </tr>
     <tr>
      <td> DOB </td>
      <td> {{s.dob}}</td>
    </tr>
     <tr>
      <td> Nationality </td>
      <td> {{s.nationality}}</td>
    </tr>
     <tr>
      <td> Address </td>
      <td> {{s.address}}</td>
    </tr>
     <tr>
      <td> Mobile No. </td>
      <td> {{s.mobileno}}</td>
    </tr>
     <tr>
      <td> EmailId </td>
      <td> {{s.email}}</td>
    </tr>
 
 

   </tbody>
</table>
</div>
</div>  
{% endblock %}

students/templates/students/retall.html

{% extends 'base.html'%}


{% block content %}
<div class=" col-md-12 col-sm-12">
  <center><h3>List of Students</h3></center>
<table class="table table-striped" >


  <tr >
    <th>Name</th>
    <th>Class</th>
    <th>Roll No</th>
    <th colspan="3" style="text-align: center;"> Actions</th>
    
  </tr>
<tbody>

{% for p in s %}
<tr>
<td>{{p.name}}</td>
<td>{{p.classinfo}}</td>
<td>{{p.rollno}}</td>
<td><a href="{% url 'students:detail' p.pk %}">View Details</a></td>
<td><a href="{% url 'students:update' p.pk %}">Update </a> </td>
<td><a href="{% url 'students:delete' p.pk %}">Delete </a> </td>
</tr>
{% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

students/templates/students/update.html
{% extends 'base.html'%}

{% block content %}
<div class=" col-md-9 col-sm-9">
 <legend>Update Your details</legend>
    <form class="site-form-create" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{from.media}}
      {{form.as_p}}
      <input type="submit" name="update" value="Update">
    </form>
   
</div>


{% endblock %}

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang ="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0 ,shrink-to-fit=no">
      <meta ht  tp-equiv="x-ua-compatible" content="ie-edge">

       <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
   
      <link rel ="stylesheet" href="{% static 'style.css' %}" >
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      
      <title>CRUD MANAGEMENT</title>
      </head>
   <body>

 
<!--Navbar-->
  
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
         
          <a class="navbar-brand" href="#"><b>CRUD MANAGEMENT</b></a>
        </div>
      </div>

</nav>

<!--Navbar -->



   
  
    <section id="main">
      <div class="container">
        <div class="panel panel-default">
  <div class="list-group-item active main-color-bg">
    <h3 class="panel-title">Dashboard</h3>
  </div>
  <center>
  <div class="panel-body">

    <div class="col-md-6">
      <div class="well dash-box">
      <a href="{% url 'students:CreateStudent' %}"   class="list-group-item"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Add Student</a>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well dash-box">
            <a href="{% url 'students:RetrieveAll' %}"  class="list-group-item"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> View Students </a>
      </div>
    </div>
  </div>

 
</center>
</div>
        
         {% block content %}

          {% endblock %}
       
     

  
  </div>
</section>
         
          
  </body>
</html>